services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-container
    ports:
      - "80:8000"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - API_KEY=${API_KEY}
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}
