name: API Tests

on:
    workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd simple-api-app/app
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov mongomock httpx requests

    - name: Run tests
      run: |
        cd simple-api-app/app
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest --cov=./ --cov-report=xml -v

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./simple-api-app/app/coverage.xml
        flags: unittests
        fail_ci_if_error: true
        retry_on_error: true
        max_retry: 3